### ISSUE TITLE
Fitur untuk absen siswa, guru, dan pegawai

### ISSUE THREAD

**Issue by msramdan** [msramdan/absensi_siswa#1]
buat kek gin mat https://www.youtube.com/watch?v=iQTbE1KXXeA
intinya fitur absen masuk dan pulang dengan QR Code dengan referensi absensi ikutin jadwal masuk yang ada pada setingan aplikasi

**Comment by rachyharkov** [comment]
siap banh

**Comment by rachyharkov** [comment]
**Done yh**
